/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export { }
declare global {
  const Toaster: typeof import('toast')['Toaster']
  const toast: typeof import('vue-sonner')['toast']
  const useDialog: typeof import('naive-ui')['useDialog']
  const useLoadingBar: typeof import('naive-ui')['useLoadingBar']
  const useMessage: typeof import('naive-ui')['useMessage']
  const useNotification: typeof import('naive-ui')['useNotification']
}
